# Numpy Array

In [1]:
import numpy as np

In [2]:
# creating an array
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
# data type of an array
arr=np.array([1,2,3,4],dtype=float)

In [5]:
arr

array([1., 2., 3., 4.])

In [6]:
# array initialization
arr=np.array([],dtype='S')

In [7]:
arr=np.arange(10,40)

In [8]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [9]:
arr=np.arange(10,40,2)

In [10]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [11]:
np.insert(arr,5,int(40))  # does not change in the original array arr

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [12]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [13]:
arr=np.append(arr,50)

In [14]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 50])

In [15]:
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 50]


In [16]:
#matrices in python

In [17]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# speed cheking-- list vs numpy array
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()  #first time is package and second one is the function in it which we are using
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

5.248394966125488


In [20]:
a1=np.arange(10000000)
b1=np.arange(10000000,20000000)
import time
start=time.time()
c1=a1+b1
print(time.time()-start)

0.025027036666870117


In [21]:
5.9949/0.0214

280.1355140186916

In [22]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
mat[1]

array([5, 6, 7, 8])

In [24]:
mat[1,2]

7

In [25]:
mat[2,3]

12

In [26]:
for i in range(3):
    print(mat[i,1])

2
6
10


# 3 dimensional array---list of 2-d arrays

In [27]:
# 3 dimensional array---list of 2-d arrays

In [28]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [29]:
d3[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
d3[1,0]

array([ 9, 10, 11, 12])

In [31]:
d3[1,0,3]

12

In [32]:
# tasks
#1-search an element in an array
#2-Find largest element in an array
#3Find smallest number in an array
#4-reversing an array
#5-rotating an array from kth position


# Tasks:-

In [33]:
#1
print("Enter the size:")
s=(int)(input())
print("Enter the elements")
for i in range(0,s):
    a[i]=(int)(input())
print("enter the element to be searched")
n=(int)(input())
c=0
for i in range(0,s):
    if(a[i]==n):
        print("element found")
        c=1
if(c==0):
    print("element not found")
    


Enter the size:
5
Enter the elements
1
2
3
4
5
enter the element to be searched
3
element found


In [34]:
#2
print("Enter the size:")
s1=(int)(input())
print("Enter the elements")
for i in range(0,s1):
    a1[i]=(int)(input())
l=a1[0]
for i in range(0,s1):
    if(a1[i]>l):
        l=a1[i]
print("Largest element is = ",l)

Enter the size:
5
Enter the elements
1
23
6
5
38
Largest element is =  38


In [35]:
#3
print("Enter the size:")
s1=(int)(input())
print("Enter the elements")
for i in range(0,s1):
    a1[i]=(int)(input())
l=a1[0]
for i in range(0,s1):
    if(a1[i]<l):
        l=a1[i]
print("Smallest element is = ",l)


Enter the size:
5
Enter the elements
12
6
8
3
9
Smallest element is =  3


In [36]:
#4
print("Enter the size:")
s1=(int)(input())
print("Enter the elements")
for i in range(0,s1):
    a1[i]=(int)(input())
j=0;
for i in range(s1-1,-1,-1):
    b1[j]=a1[i]
    j=j+1
print("Reversed array is:\n")
for i in range(0,s1):
    print(b1[i])



Enter the size:
5
Enter the elements
1
2
3
4
5
Reversed array is:

5
4
3
2
1


In [ ]:
#5
print("Enter the size:")
s1=(int)(input())
print("Enter the elements")
for i in range(0,s1):
    a1[i]=(int)(input())
print("Enter the position from which array is to be rotated:")
p=(int)(input())
p=p%s1
k=p-1
j=0
for i in range(0,s1):
    b[j]=a1[k]
    j=j+1
    k=k+1
    if(k>=s1):
        k=0
print("Rotated array is:\n")
for i in range(0,s1):
    print(b[i])

In [ ]:
3


In [ ]:
print("k")